apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ai-job-orchestrator.fullname" . }}-api-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ai-job-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ai-job-orchestrator.fullname" . }}-worker-pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: inference-worker
